### ISSUE TITLE
Excited for V16!?

### ISSUE THREAD

**Issue by seanaguinaga** [simondotm/nx-firebase#110] opened 2023-04-28 18:38 UTC
```Cannot find module '@nrwl/js/src/executors/tsc/tsc.impl'```

**Comment by simondotm** [comment] 2023-04-28 20:05
pfft - I cant keep up with Nx. They just change their APIs like no-ones watching 😆

**Comment by simondotm** [comment] 2023-04-28 20:12
Plus I'm using angular 14 so upgrading to Nx >14 seemed impossible for me, unless they fixed their migration script since I last looked

**Comment by simondotm** [comment] 2023-04-28 20:17
to be fair it looks like they're just not shipping their src in the npm package anymore, which isnt entirely unreasonable. I should look into this. Cant remember why our plugin would be accessing from src folder anyway 🤔 
v14 - https://www.npmjs.com/package/@nrwl/js/v/14.8.8?activeTab=code
v16 - https://www.npmjs.com/package/@nrwl/js/v/16.0.0?activeTab=code

**Comment by simondotm** [comment] 2023-04-28 20:18
yeah, this is a 'my bad' situation. marked as bug

**Comment by pascalbe-dev** [comment] 2023-05-05 13:23
I stumbled across this as well. As a workaround I added the old `@nrwl` dependencies as well next to the new `@nx` ones like this:

```
    "@nx/workspace": "16.1.0",
    "@nx/linter": "16.1.0",
    "@nx/js": "16.1.0",
    "@nx/cypress": "16.1.0",
    "@nx/jest": "16.1.0",
    "@nrwl/workspace": "15.9.3",
    "@nrwl/js": "15.9.3"
```

With that, I could get it running. This is just a workaround, but maybe it can help someone :-)

**Comment by simondotm** [comment] 2023-05-06 13:38
ok thanks folks, I will try to fix this as soon as I can, problem line is here: 
https://github.com/simondotm/nx-firebase/blob/77117fb0732809733b24fa3b3113c88028dd8373/packages/nx-firebase/src/executors/build/build.ts#L3

Reading the release notes for Nx 16 they seem to have finished decoupling their versioning from Angular releases, so maybe I can upgrade to 16 now and test it all.

**Comment by simondotm** [comment] 2023-05-07 12:16
Ok the latest Nx 16.1.1 finally allows updates without breaking the Angular version. I will move the plugin to this release soon.
Might also get some other issues fixed too.

**Comment by simondotm** [comment] 2023-05-07 23:08
ohhhh so the issue is that plugins are rescoped to `@nx` now instead of `@nrwl`
got it

**Closed** 2023-05-08 12:48 UTC
Labels: bug

**Comment by simondotm** [comment] 2023-05-08 12:58
Release new version 1.1.0-beta.0 https://www.npmjs.com/package/@simondotm/nx-firebase
Please let me know if any issues thx
